name: ittime
description: IT Time Application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_html: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  image_path: "Icons/logo.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  fonts:
      - family: Zilla Slab
        fonts: 
          - asset: fonts/ZillaSlab-SemiBold.ttf
 